// Builds src/worker.js from site/*.html. No runtime dependencies.
import { readFileSync, writeFileSync } from "node:fs";
const r = (p) => readFileSync(new URL(`./site/${p}`, import.meta.url), "utf8");
const style = r("_style.css").trim(), head = r("_head.html").trim(), foot = r("_foot.html").trim();
const page = (f) => r(f).replace("{{STYLE}}", style).replace("{{HEAD}}", head).replace("{{FOOT}}", foot);
const pages = { "/": page("index.html"), "/privacy": page("privacy.html"), "/terms": page("terms.html") };
const worker = `// Generated by build.mjs — do not edit. Source: site/*.html
const PAGES = ${JSON.stringify(pages)};
const HEADERS = {
  "content-type": "text/html; charset=utf-8",
  "cache-control": "public, max-age=300",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
  "x-content-type-options": "nosniff",
  "referrer-policy": "strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
};
export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (url.hostname.startsWith("www.")) {
      url.hostname = url.hostname.slice(4);
      return Response.redirect(url.toString(), 301);
    }
    let path = url.pathname.replace(/\\/+$/, "") || "/";
    if (path.endsWith(".html")) path = path.slice(0, -5) || "/";
    if (path === "/index") path = "/";
    if (path === "/robots.txt") return new Response("User-agent: *\\nAllow: /\\n", { headers: { "content-type": "text/plain" } });
    const body = PAGES[path];
    if (!body) return new Response("Not found", { status: 404, headers: { "content-type": "text/plain" } });
    return new Response(body, { headers: HEADERS });
  },
};
`;
writeFileSync(new URL("./src/worker.js", import.meta.url), worker);
console.log("built src/worker.js:", Object.keys(pages).map(k => `${k} ${pages[k].length}B`).join(", "));
