#!/usr/bin/env python3
"""The public ASR rows: the private register (workspace memory/reference/asr.md) masked by hand.
No hostnames, addresses, account or ticket ids, file paths, service labels, bucket or tunnel
names; no names beyond the operator and the agent; nothing employer-specific. Writes the
<tbody> of site/asr.html between the ASR-ROWS markers. Run: python3 tools/asr-public.py
"""
import os, html
ROWS = [
 ("ASR-001","2026-04-12","The predecessor: an agent under the same name on a chat bot, a starter kit absorbed unreviewed, one API key metered by nobody, every account and the persona on one workstation.","First deployment.","Everything at once: spend, the provider account, domains and mail, the workstation, the persona and its memory.","None existed.","superseded"),
 ("ASR-002","2026-08","The compromise: five losses from one event. Unmetered credential, credential co-location, no execution isolation, state inside the process, no blast-radius containment.","The event this register exists to never repeat.","See ASR-001.","n/a","superseded"),
 ("ASR-003","2026-09-05","Rebuild: the persona compiled from a git repository into the agent's workspace; identity and memory are files, the orchestrator process is replaceable.","State inside the process was the fourth loss.","Persona and memory.","Reinstall from git.","active"),
 ("ASR-004","2026-09-05","A written constitution with the gating principle: approval only where an action is both irreversible and external; everything else engineers its own undo.","Blast radius was the fifth loss.","Every action.","Amendment.","active"),
 ("ASR-005","2026-09-05","Vault-only secrets; the vault repository isolated from execution repositories; subscription billing preferred over API keys.","Unmetered credentials and co-location were losses one and two.","Every credential.","Principle; no undo.","active"),
 ("ASR-006","2026-09-05","The vault repository recorded as an empty placeholder, and the only infrastructure inventory marked inaccurate.","Truth over recollection.","Inventory accuracy.","n/a","active"),
 ("ASR-007","2026-09-07","The small single-board router measured: first generation, two 1 GbE ports, a factory image with eight ports open; cannot route the multi-gigabit WAN. Re-scoped as the mesh-network subnet router after a reimage.","Border and remote-access design.","Remote access path.","Reimage.","active"),
 ("ASR-008","2026-09-07","\"The consumer mesh router suffices; no gateway now.\"","Cost.","LAN and WAN.","n/a","superseded"),
 ("ASR-009","2026-09-08","Ten branches found deleted from the persona repository's remote and recovered; no backup destination for the primary host yet.","Persona repository integrity.","The persona source.","Restore from clones.","active"),
 ("ASR-010","2026-09-08","Memory engine: a local embedding model, no egress; automatic \"dreaming\" off, promotion of facts is manual.","Egress and fabrication risk.","Recall quality only.","Config toggle.","active"),
 ("ASR-011","2026-09-09","Context compaction moved to a frontier model after every earlier compaction was found to have failed on the local model.","Sessions were never compacting.","Long sessions, cost.","Config.","active"),
 ("ASR-012","2026-09-09","Bootstrap truncation fixed; the durable memory file split into sidecars; a prompt budget with a warn and a fail line, enforced by a lint that walks every place the number lives.","The injected prompt was being cut silently.","Every turn's context.","Revert the split.","active"),
 ("ASR-013","2026-09-09","A four-port gigabit NIC into the single-board router; external storage on the sandbox host; the sandbox host's console brought up over HDMI.","Router and sandbox hardware.","The lab.","Remove.","active"),
 ("ASR-014","2026-09-09","A second public domain registered at the edge provider, zone left empty.","A second public name, reserved.","One domain.","Let lapse.","active"),
 ("ASR-015","2026-09-10","The agent's workspace repository gets a private remote; pushed after every change.","Memory off the box, fourth-loss insurance.","Memory files at the code host, private.","Remove the remote.","active"),
 ("ASR-016","2026-09-11","Three model lanes: a subscription lane, a prepaid API lane, a local model; the local model removed from interactive turns after it fabricated completed actions.","Every defective turn traced to the local rung.","Answer quality, spend.","Config.","active"),
 ("ASR-017","2026-09-11","Constitution rule: inbound images are read, their facts filed, the image trashed the same turn; nearly two hundred stored images stripped across three stores.","Images were an unbounded store of personal data.","Personal photos.","Amendment.","active"),
 ("ASR-018","2026-09-11","A hypervisor decided for the sandbox host: the tier for untrusted code and the untrusted-content reader, on a quarantine VLAN first.","No execution isolation was the third loss.","What untrusted code can reach.","Reimage.","active"),
 ("ASR-019","2026-09-12","Model ladder for interactive turns, the local model never on the main session; a spend audit found harness-error fallbacks paying twice.","Cost, one voice.","Spend.","Config.","active"),
 ("ASR-020","2026-09-12","Memory taxonomy: eight labels, proposed by a peer agent, adopted; chat rooms map one to one onto the labels.","Findability across two agents.","Memory layout.","Rename.","active"),
 ("ASR-021","2026-09-12","iMessage channel live; a separate family workspace so private memory never loads in a shared room.","Shared rooms must not see private memory.","Private memory.","Unbind.","active"),
 ("ASR-022","2026-09-12","Discord: application and bot, rooms built by hand, direct messages allowlisted to the operator, admin actions only from a live in-guild turn.","A second shared surface.","Memory exposure through a direct message.","Remove the channel block.","active"),
 ("ASR-023","2026-09-12","A knowledge-vault CLI installed; the compiled memory wiki lives in a local vault.","Human-browsable knowledge.","Wiki only.","Uninstall.","active"),
 ("ASR-024","2026-09-12","A research corpus repository's history squashed, with a bundle backup taken first; a runaway hook fixed.","Repository hygiene, and a backup before a destructive operation.","Corpus history.","Restore the bundle.","active"),
 ("ASR-025","2026-09-12","Family calendar frame bridge live: a morning headline push and a sync-down, hard-ruled to the household's four profiles; the credential only through the egress proxy.","Family calendar on the frame.","The frame's calendar and its credential.","Disable the automations.","active"),
 ("ASR-026","2026-09-12","Rule from a lost reply: channel configuration changes come from an isolated session, never the main turn.","An upstream bug drops the reply on a deferred reload.","Reply delivery.","n/a","active"),
 ("ASR-027","2026-09-13","Firewall: no appliance purchase; the mesh router stays layer 3 for now; an open-source firewall later as a VM; the single-board unit becomes the subnet router plus DNS, NTP and syslog.","Spend, and the border sequence.","Border.","n/a","superseded"),
 ("ASR-028","2026-09-13","A password manager is the credential path for every account except the core financial ones, which arrive only as photos; a hardware key holds the vault identity.","Co-location, with a usable path.","Every credential.","Rotate.","active"),
 ("ASR-029","2026-09-13","Heartbeat moved off the local model to a frontier model, every five hours; labels on posts instead of new channels.","Heartbeat quality.","Heartbeat.","Config.","active"),
 ("ASR-030","2026-09-13","Disaster-recovery runbook for rebuilding the host; platform updated; memory folds scheduled daily and weekly.","The fourth-loss defence made operational.","Host rebuild.","n/a","active"),
 ("ASR-031","2026-09-13","Personal finance ledger in plain text with a local web viewer on loopback; the finance directory is never a git repository and raw files are encrypted at rest.","Finance on the box only.","Figures on the box only.","Unload the agent.","active"),
 ("ASR-032","2026-09-15","A dedicated gateway becomes the border, superseding \"the mesh router suffices\"; an open-source firewall scoped for the single-board unit; a 24-port switch and a 10G module inventoried.","Availability and a real border.","LAN segmentation, WAN.","Re-cable to the old router.","active"),
 ("ASR-033","2026-09-13","The persona repository re-homed under the right owner; the operator's full professional-network export unpacked locally, mode 700.","Persona sources under the right owner; the export is the résumé's source of truth.","Persona repository; personal data on disk.","Move back.","active"),
 ("ASR-034","2026-09-13","A self-hosted chat front end on the inference host, loopback only, local models, sign-up off; a workflow-automation tool dropped.","The lab's front door; persona A/B testing.","Chat history on an encrypted disk.","Stop the container.","active"),
 ("ASR-035","2026-09-13","A review room on Discord for artifacts; the iMessage group for conversation. Later found the peer agent does not read Discord.","A review home.","n/a","n/a","active"),
 ("ASR-036","2026-09-13","The operator's directive file and the durable memory file had been marked untrusted and silently not injected; fixed, and the real prompt prefix measured.","The twin was running without its own directives.","Every turn.","n/a","active"),
 ("ASR-037","2026-09-13","Out-of-band KVM console and a multiport switch arrived for the sandbox host and the cluster; busy-lights, a Z-Wave controller and e-ink displays inventoried.","Console before installer.","Sandbox-host recovery path.","Unplug.","active"),
 ("ASR-038","2026-09-14","ARM cluster physical layout and storage plan v1.2; the buy list rewritten to match what was inbound.","The cluster's shape.","Cluster.","Plan revision.","active"),
 ("ASR-039","2026-09-14","Wiki maintenance loop fixed: every vault command needs an explicit agent; syntheses are hand-authored; the CLI's open command is broken, the URL scheme works.","A publishable vault.","Wiki.","n/a","active"),
 ("ASR-040","2026-09-15","A read-only card-transaction feed into the ledger on a schedule; credentials fetched from the password manager at run time; a validator gates every write; a receipt register.","Transactions without manual entry.","Ledger integrity.","Unload the agent.","active"),
 ("ASR-041","2026-09-16","Employer material handed over by the operator is stored encrypted and offline under a custody rule, never refused; employer systems are never touched from the lab.","One agent serving two contexts needs a wall between them.","Employer confidentiality.","Amendment.","active"),
 ("ASR-042","2026-09-16","A second household member enters the family agent's pipeline (persona rules, a first-contact plan); the peer group's mention gate turned off.","A new person on a shared surface.","The family agent surface.","Revert.","active"),
 ("ASR-043","2026-09-16","Two small firewall appliances considered and not bought; a 6U rack, the UPS fleet and the upstairs network closet inventoried.","Spend held for the gateway path.","n/a","n/a","held"),
 ("ASR-044","2026-09-17","The company formed (WA); a cloud project exists under its name; smart-home devices to a home-automation hub proposed as a project.","The business and its cloud account.","Company records; one cloud project.","n/a","active"),
 ("ASR-045","2026-09-18","This site live: one edge worker with static assets, apex and www, email routing; code-activity graphs fetched at build; a mistyped worker that had held the domain bindings deleted.","A public site as the hiring instrument.","Public content.","Delete the worker and DNS.","active"),
 ("ASR-046","2026-09-18","Secrets root cause: the subscription-lane sessions never receive credential sentinels; deploys run in a prepaid-lane child with gateway execution and the token as an opaque proxy sentinel. Written into the working rules.","Hold losses one and two while still being able to deploy.","Edge-provider token exposure.","n/a","active"),
 ("ASR-047","2026-09-18","A trajectory ledger and a receipt verifier: a completion claim needs a verified receipt; a ground-truth corpus from the peer agent.","Two false completion receipts in one night.","Every \"done\".","n/a","active"),
 ("ASR-048","2026-09-18","Satellite dish and router in place with the account closed; recorded as the second-WAN failover candidate, reactivation gated as spend.","So the \"no failover WAN\" answer is known to be a choice, not an absence.","WAN2.","n/a","held"),
 ("ASR-049","2026-09-18","Rack build started; the exterior demarcation documented.","Physical plant.","n/a","n/a","active"),
 ("ASR-050","2026-09-19","The main session runs with no fallback chain, never to be re-added: the reply-drop bug makes every fallback a paid duplicate run.","Cost.","Answer availability.","Config.","active"),
 ("ASR-051","2026-09-20","The scheduled tier moved off the metered API: eleven automations moved to script payloads, a command payload, or the subscription lane.","\"I don't want cron jobs on an API burning money.\"","Spend.","Config.","active"),
 ("ASR-052","2026-09-20","A private household portal behind an identity gate (one-time codes), a small database for lists and notes, transactional email for notifications.","A back office for the household behind identity, not network.","Household lists and notes.","Delete the worker and the identity app.","active"),
 ("ASR-053","2026-09-20","A hosted newsletter service for email subscriptions; sending-domain DNS still pending.","Zero-build subscriber list.","Subscriber emails at a third party.","Export and close.","active"),
 ("ASR-054","2026-09-20","Infrastructure as Music: a live-coding synth driven over its local API, phrases for deploy, fault and recover, a state drone, nightly episodes published to Code as Music.","Sound generated from lab state, never a playlist.","Audio on the box only.","Stop.","active"),
 ("ASR-055","2026-09-20","Three sites, one estate: the public site, the private portal, a reserved domain; a product-demo site held pending a conflict-of-interest disclosure.","Audience split.","n/a","n/a","active"),
 ("ASR-056","2026-09-20","iMessage group ingress went stale for four hours; recovery documented; a stale-ingress check is the follow-up.","\"Why aren't you picking up iMessages?\"","Shared-room availability.","n/a","active"),
 ("ASR-057","2026-09-21","Sub-agent roster renamed to a Salish Sea set of five; exactly one of them holds keys.","Naming, and a single keyed courier.","Deploy path.","Rename.","active"),
 ("ASR-058","2026-09-21","A second household member added to the family agent's allowlist.","Direct contact instead of relay.","The family agent surface.","Remove from the allowlist.","active"),
 ("ASR-059","2026-09-21","An outbound-only tunnel exposes the chat front end on a hostname behind an operator-only identity app. First lab service on a public hostname; identity-gated, not network-gated; an explicit exception to the \"no lab service on the public internet\" rule, approved by the operator.","The front end as a standalone view from the portal.","Chat history, local models, and through a finance tool, ledger figures. Trigger: the operator's identity or the edge account compromised.","Unload the tunnel agent; delete the tunnel, the DNS record, the identity app.","active"),
 ("ASR-060","2026-09-21","A file-serving route on the portal that had been missing for four hours (files bundled, route never added, everything answered 404 behind the gate) was added; per-person access is enforced in code because the identity app admits both household members.","A private folder must be private to one person.","One person's files.","Remove the route.","active"),
 ("ASR-061","2026-09-21","Object storage enabled on the edge account and bound to the portal: phone uploads into one person's private folder.","Phone uploads need object storage; the small database cannot hold them.","A new store off the box holding personal media. Reach: whoever holds the edge account or that person's identity. Free tier, no card.","Delete the bucket and the binding.","active"),
 ("ASR-062","2026-09-21","Portal areas added: a projects view (static export of the lab's notes, wiki and diagrams), a career map (aggregate only), a tile to the chat front end.","A human view of the lab's state; a career plan with dependencies.","Portal content only; the aggregate rule holds.","Remove the areas.","active"),
 ("ASR-063","2026-09-21","Favicon kit on this site: root icon, aliases, web manifest, theme colour.","Browser branding.","None.","Revert.","active"),
 ("ASR-064","2026-09-21","Fan-out plan: one source of truth (git), six derived surfaces (code host, knowledge vault, chat rooms, chat front end, two sites); the finance lane walled off to the local viewer and derived aggregates.","Keep every surface current from one source.","n/a","n/a","proposed"),
 ("ASR-065","2026-09-21","This page, identifiers masked; and the register played as music, regenerated from the table.","\"Promote the logging of ASR … to be transparent.\"","Public content; the masking rule is the boundary.","Remove the page.","active"),
 ("ASR-066","2026-09-21","The synth's audio engine found dead since the previous evening, every phrase since then silent while the API check said \"up\"; relaunched; the check now requires the engine process.","A liveness check on the API is not a check on the instrument.","Lab audio.","n/a","active"),
]
def row(r):
    i, d, ch, why, reach, undo, st = r
    e = html.escape
    return f'      <tr><td>{i}</td><td>{d}</td><td>{e(ch)}</td><td data-l="Why">{e(why)}</td><td class="reach" data-l="Reach">{e(reach)}</td><td data-l="Undo">{e(undo)}</td><td><span class="st {st}">{st}</span></td></tr>'
p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "site", "asr.html")
s = open(p).read()
a, b = "<!-- ASR-ROWS -->", "<!-- /ASR-ROWS -->"
body = "\n" + "\n".join(row(r) for r in reversed(ROWS)) + "\n    "  # newest first (Alex, 2026-09-21)
s = s[: s.index(a) + len(a)] + body + s[s.index(b):]
open(p, "w").write(s)
print(f"{len(ROWS)} rows")
